"""JS file emitter — writes datos_zonificacion_official.js in viewer-compatible format."""
from __future__ import annotations

import json
from pathlib import Path

import geopandas as gpd


# Mirror the 13 CS2 zones from src/zoning/zones.py
CS2_ZONES = [
    "res_low_house", "res_row", "res_med", "res_mixed",
    "res_low_rent", "res_high",
    "com_low", "com_high",
    "office_low", "office_high",
    "industrial",
    "prk_surface", "prk_ramp",
]

COORD_PRECISION = 5  # 5 decimals ≈ 1.1m at the equator


def _polygon_to_coords(geom) -> list:
    """Convert a Shapely Polygon/MultiPolygon to a list of [lat, lon] pairs.

    Uses the outer ring only (no holes — viewer ignores them).
    Coords are truncated to COORD_PRECISION decimal places.
    """
    if geom.geom_type == "Polygon":
        rings = [geom.exterior]
    elif geom.geom_type == "MultiPolygon":
        largest = max(geom.geoms, key=lambda p: p.area)
        rings = [largest.exterior]
    else:
        return []

    return [
        [round(y, COORD_PRECISION), round(x, COORD_PRECISION)]
        for x, y in rings[0].coords
    ]


def emit(gdf: gpd.GeoDataFrame, out_path: Path, source_name: str) -> None:
    """Write the GeoDataFrame as datos_zonificacion_official.js.

    Args:
        gdf: Must have `cs2_zone` column and be in EPSG:4326.
        out_path: Output file path (will be overwritten).
        source_name: Human-readable name of the data source for the header comment.
    """
    lines: list[str] = [
        f"// Official zoning data — source: {source_name}",
        f"// Generated by official_zoning.emitter. Do not edit by hand.",
        "",
    ]

    for zone in CS2_ZONES:
        subset = gdf[gdf["cs2_zone"] == zone]
        records = []
        for _, row in subset.iterrows():
            coords = _polygon_to_coords(row.geometry)
            if not coords:
                continue
            records.append({"coords": coords})

        var_name = f"DATA_OFFICIAL_{zone.upper()}"
        # Use `var` (not `const`) so the global is attached to `window` and
        # the visualizer's hook can find it via `window[var_name]`.
        records_json = json.dumps(records, separators=(",", ":"))
        lines.append(f"var {var_name} = {records_json};")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
